name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Build Web App
        env:
          TELEPHONE_NUMBER: ${{ secrets.TELEPHONE_NUMBER }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: flutter build web --dart-define=GITHUB_LINK=https://github.com/rafaelortizzableh --dart-define=LINKEDIN_LINK=https://linkedin.com/in/rafaelortizzableh --dart-define=TWITTER_LINK=https://twitter.com/ortizzableh --dart-define=PHONE_LINK=tel:$TELEPHONE_NUMBER --dart-define=EMAIL_LINK=mailto:$EMAIL_ADDRESS 

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_ROZ }}'
          projectId: portfolio-roz
